# *`NumPy Array Functions & Splitting`*
---

### **1. Splitting Arrays**

In [38]:
import numpy as np

In [39]:
a = np.arange(12).reshape(3 , 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
axis0 = np.vsplit(a , 3)
axis0

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [41]:
axis1 = np.hsplit(a , 4)
axis1


[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [42]:
axis1[0]

array([[0],
       [4],
       [8]])

In [43]:
axis1[0].ndim

2

In [44]:
axis1[0].shape

(3, 1)

In [45]:
axis1[0].dtype

dtype('int64')

In [46]:
type(axis1[0])

numpy.ndarray

In [47]:
type(axis1)

list

In [48]:
axis1[0][2]

array([8])

In [49]:
axis1[0][2].dtype

dtype('int64')

---

In [57]:
a.sum()

np.int64(60)

In [59]:
a.prod()

np.int64(0)

In [60]:
a.diagonal()

array([ 0,  5, 10])

In [61]:
a.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 30, 39, 49, 60])

In [70]:
b = np.arange(1 , 10)
b.cumprod()

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

In [ ]:
np.array([1 , 3 , 5 , 7 , 9]) #list convert array

array([1, 3, 5, 7, 9])

In [ ]:
np.array((1 , 3 , 5 , 7 , 9)) #tuple convert array

array([1, 3, 5, 7, 9])

In [74]:
np.array({'name':'Ammad'})

array({'name': 'Ammad'}, dtype=object)

In [ ]:
np.array([1 , 'a' , True , 3.1]) #list main multiple data types store kr skty hain.

array(['1', 'a', 'True', '3.1'], dtype='<U32')

In [89]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [90]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

---

In [122]:
x = np.array([[1 , 2 , 3] , [4 , 5.7 , 6]]) #float ko high priority mili ha
print(f'Important:\n{'-'*100}\nfloat ko high priority mili ha.')
x

Important:
----------------------------------------------------------------------------------------------------
float ko high priority mili ha.


array([[1. , 2. , 3. ],
       [4. , 5.7, 6. ]])

In [104]:
x.shape

(2, 3)

In [105]:
np.ones_like(x)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [106]:
np.zeros_like(x)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [111]:
np.full_like(x,9)

array([[9., 9., 9.],
       [9., 9., 9.]])

---