# **NumPy Array Combine & Reshaping**

In [1]:
import numpy as np

In [2]:
array2d = np.arange(64).reshape(8 , 8)
array2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [3]:
array2d > 50

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [4]:
array2d[array2d > 50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [5]:
array2d[array2d%5 == 0]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [6]:
array2d[array2d%7 == 1]

array([ 1,  8, 15, 22, 29, 36, 43, 50, 57])

In [ ]:
array2d[array2d%2 > 0] #Odd Numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63])

In [ ]:
array2d[array2d%2 == 0] #Even Numbers

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62])

In [12]:
array2d[array2d%2 > 0] + array2d[array2d%2 == 0]

array([  1,   5,   9,  13,  17,  21,  25,  29,  33,  37,  41,  45,  49,
        53,  57,  61,  65,  69,  73,  77,  81,  85,  89,  93,  97, 101,
       105, 109, 113, 117, 121, 125])

In [18]:
array2d[(array2d%5 == 0) & (array2d%7 != 0)]

array([ 5, 10, 15, 20, 25, 30, 40, 45, 50, 55, 60])

# RESHAPE ARRAY

In [19]:
a = np.arange(0 , 9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a.shape #No Dimensions / Only 9 elements

(9,)

In [25]:
b = a.reshape(3 , 3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
b.shape #Dimensions

(3, 3)